In [22]:
import numpy as np

A = np.array([1, 2, 3, 4]).reshape(2,2)
B = 100

print(f'A:\n {A}')
print(f'A transpose:\n {A.T}')
print(f'A+B:\n {A+B}')
print(f'sin(A^2):\n {np.sin(A ** 2)}')

dataset = np.loadtxt('../dataset/mall_customers.csv', delimiter=',')
print(f'dataset:\n{dataset}')

A:
 [[1 2]
 [3 4]]
A transpose:
 [[1 3]
 [2 4]]
A+B:
 [[101 102]
 [103 104]]
sin(A^2):
 [[ 0.84147098 -0.7568025 ]
 [ 0.41211849 -0.28790332]]
dataset:
[[ 19.  15.  39.]
 [ 21.  15.  81.]
 [ 20.  16.   6.]
 [ 23.  16.  77.]
 [ 31.  17.  40.]
 [ 22.  17.  76.]
 [ 35.  18.   6.]
 [ 23.  18.  94.]
 [ 64.  19.   3.]
 [ 30.  19.  72.]
 [ 67.  19.  14.]
 [ 35.  19.  99.]
 [ 58.  20.  15.]
 [ 24.  20.  77.]
 [ 37.  20.  13.]
 [ 22.  20.  79.]
 [ 35.  21.  35.]
 [ 20.  21.  66.]
 [ 52.  23.  29.]
 [ 35.  23.  98.]
 [ 35.  24.  35.]
 [ 25.  24.  73.]
 [ 46.  25.   5.]
 [ 31.  25.  73.]
 [ 54.  28.  14.]
 [ 29.  28.  82.]
 [ 45.  28.  32.]
 [ 35.  28.  61.]
 [ 40.  29.  31.]
 [ 23.  29.  87.]
 [ 60.  30.   4.]
 [ 21.  30.  73.]
 [ 53.  33.   4.]
 [ 18.  33.  92.]
 [ 49.  33.  14.]
 [ 21.  33.  81.]
 [ 42.  34.  17.]
 [ 30.  34.  73.]
 [ 36.  37.  26.]
 [ 20.  37.  75.]
 [ 65.  38.  35.]
 [ 24.  38.  92.]
 [ 48.  39.  36.]
 [ 31.  39.  61.]
 [ 49.  39.  28.]
 [ 24.  39.  65.]
 [ 50.  40.  55.]
 [

In [21]:
np.mean(A, axis=1, keepdims=True)


array([[1.5],
       [3.5]])